#!/bin/sh

# DEFINE MODEL FOR WHICH INPUT IS READ IN: *1* = UrQMD, *2*= SMASH
export model=2

#FOR SMASH: NEED TO DEFINE ECM AND TRANSFORMATION BETA
export ecm=10
export betalab=0.0292914

# VACUUM OR MEDIUM CALCULATION? *0*= MEDIUM SPECTRAL FUNCTION, *1*=RHO VACUUM SF
# CAUTION: VACUUM CALCULATION ONLY POSSIBLE FOR ELETSKY SF; FOR RAPP SF MUST BE 1!
export vacuum=0

# NUMBER OF CELLS IN X AND Y DIRECTION. FOR Z-AXIS, THE VALUE IS MULTIPLIED BY 3
export gridsize=20  # 50

# LENGTH OF GRID CELLS (x=y=z), IN FM
export cellsize=0.7d0  # 0.7

# EQUATION OF STATE FOR DETERMINING T AND MU_B:
# *1* = ULTRARELATIVISTIC GAS (NOT RECOMMENDED!)
# *2* = HADRON GAS EoS --> only hadronic emission (ONLY USE FOR VERY LOW ENERGIES, 1-2 AGeV, WHERE ALL CELLS WITH T < 170 MeV, OR FOR A PURE HADRONIC SCENARIO)
# *3* = CHIRAL EoS (NOT RECOMMENDED!)
# *4* = HG EoS (as for *2*), but QGP emission above T_c (RECOMMENDED FOR LOW ENERGIES - SIS / FAIR)
# *5* = CHIRAL EoS + ONLY QGP above T_c (NOT RECOMMENDED!)
# *6* = HG EoS + QGP from LATTICE EoS above T_c (RECOMMENDED FOR HIGH ENERGIES - SPS / RHIC / LHC )
export eos=6

# CHOOSE EMISSION TYPE AND RATES:
# *-1* = PHOTON EMISSION
# *0*  = DILEPTON EMISSION with ELETSKY spectral function
# *1*  = DILEPTON EMISSION with **OLD** RAPP spectral function (rho, omega and phi) - DO NOT USE ANY LONGER!
# *2*  = DILEPTON EMISSION with **OLD** RAPP spectral function for high resolution rho and omega - DO NOT USE ANY LONGER!
# *3*  = DILEPTON EMISSION with **NEW** RAPP spectral function for phi only
# *4*  = DILEPTON EMISSION with **NEW** RAPP spectral function for rho and omega - high mass resolution
export rates=4

# USE FINITE VALUES FOR MU_PI AND MU_K? *1* = YES (RECOMMENDED), *0* = NO
export pikchem=1

# CONSIDER FINITE BARYON DENSITY / MU_B EFFECTS? *1* = YES (RECOMMENDED), *0* = NO
export baryons=1

# WRITE DILEPTON / PHOTON OUTPUT f71? *1* = YES, *0* = NO
# (IF NO, ONLY CELL PROPERTIES AND NON-THERMAL f72 CALCULATED)
export output=1

##################################
##### FOR PHOTON CALC. ONLY: #####
##################################

# CHOOSE QGP RATES: *1* = FULL QGP RATE, *0* = SIMPLE pQCD RATE
export phqgp=1

# HADRON GAS PARAMETRIZATION: MUST BE *1* !!! (ONLY RAPP / TURBIDE
# RATES IMPLEMENTED)
export hgpar=1

####################################
##### FOR DILEPTON CALC. ONLY: #####
####################################

# CHOOSE LEPTON TYPE: *0* = DIELECTRON, *1* = DIMUON
export leptype=0

# CHOOSE MESON GAS (MULTI-PION RATES): *0* = (SAME AS IN SANTINI),
# *1* = V-A-MIXING(SAME AS FOR HEES+RAPP CALCULATIONS - DEFAULT)
export fourpimix=1

# CHOOSE QGP RATES: *0* = PERTURBATIVE RATES, *1* = LATTICE RATES (DEFAULT)
export latqgp=1

# NA60 SELECTION OF EVENTS? *0* = NO SELECTION, *1* = USE ONLY EVENTS WITH
# dN_ch/dy > 30 (for |y|<0.5), *2* = NO SELECTION, BUT WRITE OUT dN_ch/dy
export na60mode=2

##################################
##### SPECIFIC OUTPUT FILES: #####
##################################

export rhonuc=0
# *.F71 = MAIN THERMAL DILEPTON OUTPUT FILE
export ftn71=dileptons_ENERGY.f71

# DEFINE SEED FOR RANDON NUMBER GENERATOR
export random=$(printf '%d' 0x$(xxd -l 3 -ps -c 10 /dev/urandom))
#export random=123456789

export inputFile='../../dileptons_teste/DynFlu0.5/ENERGY/Hydro/1/for_dilrates.dat'

### DEFINE INPUTFILE (URQMD-F14 OR SMASH-OSCAR) AND STANDARD OUTPUTFILE HERE.
### NOTE THAT THE STANDARD OUTPUT CONTAINS ONLY THE PROPERTIES FOR EACH
### SPACE-TIME CELL; THE DILEPTON RESULTS ARE WRITTEN IN THE F71-FILE.
cat SMASH_AuAu_10.oscar | ./teste_dil > outputfile.out

exit
